I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script call
    call expression EventOne.Block
  File "game/script.rpy", line 17, in script call
    call expression EventOne.Block
ScriptError: could not find label 'EveOne'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script call
    call expression EventOne.Block
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/ast.py", line 1490, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 17, in script call
    call expression EventOne.Block
  File "/Users/daveshields/Documents/RenPy/renpy-7.4.9-sdk/renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'EveOne'.

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 7.4.9.2142
Thundy Calendar 1.0
Mon Oct 18 17:20:49 2021
